site_name: Oracle Thoughts
site_url: https://jgebal.github.io/oraclethoughts
site_author: Jacek Gebal
site_description: Oracle database, PL/SQL development, unit testing and utPLSQL
repo_url: https://github.com/jgebal/oraclethoughts
repo_name: jgebal/oraclethoughts
extra_css:
  - stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: G-1TEVWKPL97
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/utPLSQL/utPLSQL/discussions/new?category=documentation-feedback" target="_blank" rel="noopener noreferrer">GitHub Discussions</a>.
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
theme:
  name: material
  logo: assets/logo-thinking-smile.png
  favicon: assets/logo-thinking-smile.png
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: deep orange
    accent: orange
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: deep orange
    accent: orange
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  - media: "(prefers-color-scheme)"
    accent: orange
    toggle:
      icon: material/brightness-auto
      name: Switch to system preference
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
  - blog:
      blog_toc: true
  - tags
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - tables
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Blog:
      - blog/index.md
  - About: about.md
